general:
  project_name: "Tesseract"
  model: "shap-e"
  base_model : "text300M"
  transmitter : "transmitter"
  seed: 42

device:
  use_cuda: true
  fallback_to_cpu: true

diffusion:
  config_type: "diffusion"

latents:
   batch_size: 4
  guidance_scale: 15.0
  use_fp16: true
  use_karras: true
  karras_steps: 64
  clip_denoised: true
  progress: true
  sigma_min: 1e-3
  sigma_max: 160
  s_churn: 0.0